[package]

name = "iron_llvm"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies]
libc = "0.1.10"
llvm-sys = "60.0.0"

[build-dependencies]
cmake = "0.1.12"
