[package]

name = "iron_llvm"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies]
llvm-sys = "40"
libc= "0.2.39"

[build-dependencies]
cmake = "0.1.12"
